kafka:
  bootstrap-servers: kafka:29092
  consumer:
    group-id: "default"
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring:
        json:
          value:
            default:
              type: "com.github.db_service.dto.Message"
          type:
            mapping: "com.github.kafka_service.dto.Message:com.github.db_service.dto.Message"
          trusted:
            packages: "com.github.kafka_service.dto.Message"

topic:
  name: limbo